<?php

use Illuminate\Database\Seeder;
const JURUSAN = [
    'nama_jurusan' => [
        'Kedokteran',
        'Kedokteran Gigi',
        'Kedokteran Hewan',
        'Kesehatan Masyarakat',
        'Kesehatan Lingkungan',
        'Ilmu Gizi',
        'Keselamatan & Kesehatan Kerja',
        'Ilmu Keperawatan',
        'Farmasi',
        'Kedokteran Hewan',
        'Nutrisi dan Teknologi Pangan',
        'Kebidanan',
        'Fisioterafi',
        'Ilmu Keolahragaan',
        'Teknik Radiodiagnostik dan Radioterapi',
        'Manajemen Pelayanan Rumah Sakit',
        'Matematika & IPA (MIPA)	Matematika',
        'Fisika',
        'Kimia',
        'Biologi',
        'Statistika',
        'Astronomi',
        'Bioteknologi',
        'Geofisika',
        'Meteorologi',
        'Geografi',
        'Biokimia',
        'Metrologi',
        'Aktuaria',
        'Statistika Terapan',
        'Mikrobiologi',
        'Bioentrepreneurship',
        'Ilmu Pangan (Food Science)',
        'Matematika Bisnis',
        'Fisika Medis',
        'Kartografi dan Penginderaan Jauh',
        'Pengelolaan dan Pemberdayaan SDA dan Lingkungan',
        'Sosial dan Humaniora',
        'llmu Politik',
        'Filsafat',
        'Kriminologi',
        'Psikologi',
        'Ilmu Hukum',
        'Sosiologi',
        'Jurnalistik',
        'Antropologi',
        'Hubungan Internasional (HI)',
        'Ilmu Kesejahteraan Sosial',
        'Ilmu Pemerintahan',
        'Administrasi Publik',
        'Administrasi Bisnis',
        'Ilmu Komunikasi',
        'Hubungan Masyarakat',
        'Marketing Communication',
        'Penyiaran (Broadcasting)',
        'Periklanan (Advertiing)',
        'Peradilan Agama',
        'Politik Islam',
        'Pembangunan Sosial dan Kesejahteraan',
        'Business Law',
        'Manajemen Komunikasi',
        'Branding',
        'Kearsipan',
        'Sains Komunikasi dan Pengembangan Masyarakat',
        'Ilmu Keluarga dan Konsumen',
        'Manajemen Produksi Media',
        'Ekonomi dan Bisnis	Akuntansi',
        'Manajemen Keuangan',
        'Menajemen Sumber Daya Manusia dan Organisasi',
        'Manajemen Operasi',
        'Manajemen Pemasaran',
        'Administrasi Fiskal',
        'Ekonomi',
        'Bisnis Internasional',
        'Manajemen Informatika',
        'Ekonomi Pembangunan',
        'Techopreneurship',
        'Green Economy',
        'Manajemen Bisnis',
        'Administrasi Niaga',
        'Manajemen Keuangan Syariah',
        'Bisnis Islam',
        'Business Creation',
        'Kewirausahaan',
        'Manajemen Bisnis dan Pemasaran',
        'Manajemen Bisnis Internasional',
        'Ekonomi Syariah',
        'Keuangan',
        'Pemasaran Internasional',
        'Ekonomi Bisnis',
        'Akuntansi Bisnis',
        'Manajemen Pariwisata',
        'Manajemen',
        'Manajemen Transportasi',
        'Akuntansi Sektor Publik',
        'Manajemen Industri Katering',
        'Administrasi Keuangan',
        'Manajemen Bisnis Telekomunikasi Informatika',
        'Sastra dan Budaya	Ilmu Sejarah',
        'Sastra Inggris',
        'Arkeologi',
        'Sastra Jawa',
        'Sastra Arab',
        'Sastra Jepang',
        'Sastra Indonesia',
        'Sastra Rusia',
        'Sastra Perancis',
        'Sastra Korea',
        'Sastra Jerman',
        'Sastra Belanda',
        'Sastra Cina',
        'Sastra Sunda',
        'Sastra Bali',
        'Sastra Slavia',
        'Sastra Minangkabau',
        'Sastra Nusantara',
        'Sejarah dan Kebudayaan Islam',
        'Komputer dan Teknologi	Teknik Informatika',
        'Mobile Application & Technology',
        'Sistem Informasi (Manajemen Informatika)',
        'Teknologi Game',
        'Ilmu Komputasi',
        'Cyber Security',
        'Bioinformatika',
        'Sistem Komputer (Teknik Komputer)',
        'Sistem Informasi Bisnis',
        'Software Engineering',
        'Sistem dan Teknologi Informasi',
        'Computerized Accounting',
        'Information Systems Audit',
        'Accounting Information',
        'Audio Engineering',
        'Ilmu Komputer',
        'Human Computer Interaction',
        'Pendidikan	Pendidikan Guru Sekolah Dasar (PGSD)',
        'Manajemen Pendidikan',
        'Kurikulum dan Teknologi Pendidikan',
        'Pendidikan Luar Sekolah',
        'Pendidikan Luar Biasa (PLB)',
        'Pendidikan Anak Usia Dini (PAUD)',
        'Administrasi Pendidikan',
        'Pendidikan Bimbingan Konseling',
        'Ilmu Perpustakaan',
        'Teologi',
        'Pendidikan Kependudukan',
        'Tafsir Hadits',
        'Pendidikan Pancasila dan Kewarganegaraan',
        'Pendidikan Agama Islam',
        'Pendidikan Kepelatihan Olahraga',
        'Pendidikan Jasmani Kesehatan dan Rekreasi',
        'Pendidikan Ilmu Pengetahuan Alam',
        'Pendidikan Bahasa Inggris',
        'Pendidikan Bahasa dan Sastra Indonesia',
        'Pendidikan Sejarah',
        'Pendidikan Matematika',
        'Manajemen Pendidikan Islam',
        'Pendidikan Geografi',
        'Pendidikan Bahasa Arab',
        'Pertanian	Agronomi dan Hortikultura',
        'Mikrobiologi Pertanian',
        'Agribisnis (Sosial Ekonomi Pertanian)',
        'Agroteknologi',
        'Ilmu Kelautan',
        'Peternakan',
        'Agroeteknologi',
        'Kehutanan',
        'Budidaya Perairan (Akuakultur)',
        'Teknologi Pangan',
        'Rekayasa Pertanian',
        'Teknologi Pasca Panen',
        'Teknologi Hasil Hutan',
        'Silvikulutur',
        'Konservasi Sumberdaya Hutan dan Ekowisata',
        'Ilmu Hama dan Penyakit Tumbuhan (Proteksi Tanaman)',
        'Teknologi Industri Pertanian (Agroindustri)',
        'Manajemen Sumberdaya Lahan (Ilmu Tanah)',
        'Teknologi Hasil Perikanan',
        'Agrobisnis Perikanan (Sosial Ekonomi Perikanan)',
        'Pengelolaan Hutan',
        'Pemanfaatan Sumberdaya Perikanan',
        'Teknologi Industri Benih',
        'Produksi Ternak',
        'Teknologi Hasil Ternak',
        'Rekayasa Pertanian',
        'Budidaya Perikanan',
        'Manajemen Sumber Daya Perairan',
        'Manajemen Hutan',
        'Penyuluhan dan Komunikasi Pertanian',
        'Teknik Pertanian',
        'Manajemen Bisnis Unggas',
        'Profesi dan Ilmu Terapan',
        'Pendidikan Kepolisian',
        'Pendidikan Militer',
        'Penerbang (Pendidikan Pilot)',
        'Pendidikan Intelijen',
        'Komunikasi Penerbangan',
        'Lalu Lintas Udara',
        'Manajemen Logistik',
        'Desain Interior',
        'Desain Produk',
        'Furniture Design',
        'Tata Boga',
        'Desain Grafis',
        'Animasi',
        'DKV Creative Advertising',
        'Teknik	Teknik Pertambangan',
        'Teknik Kelautan',
        'Teknik Lingkungan',
        'Teknik Metalurgi',
        'Teknik Sipil',
        'Arsitektur',
        'Teknik Geodesi',
        'Teknik Elektro',
        'Teknik Mesin',
        'Teknik Industri',
        'Teknik Perkapalan',
        'Teknik Perencanaan Wilayah dan Kota (Planologi)',
        'Teknik Penerbangan (Aeronautika dan Astronautika)',
        'Oseanografi',
        'Teknik Nuklir',
        'Teknik Geologi',
        'Teknik Otomotif',
        'Teknobiomedik',
        'Teknik Perancangan Jalan dan Jembatan',
        'Teknik Refrigerasi dan Tata Udara',
        'Teknik Telekomunikasi',
        'Teknologi Bioproses',
        'Teknik Grafika',
        'Transportasi Laut',
        'Teknik Otomasi Manufaktur dan Mekatronika',
        'Rekayasa hayati',
        'Teknik Material',
        'Automotive and Robotics Engineering',
        'Teknik Tenaga Listrik',
        'Teknik Sistem Komputer',
        'Manajemen Rekayasa Industri',
        'Teknik Bioenergi dan Kemurgi',
        'Industrial RoboticsDesign',
        'Teknik Kimia',
        'Teknik Fisika',
        'Teknik Geomatika',
        'Teknik Perminyakan',
        'Teknik Alat Berat',
        'Rekayasa Infrastruktur Lingkungan',
        'Teknik Pesawat Udara',
        'Teknik Telekomunikasi dan Navigasi Udara',
        'Teknik Bangunan dan Landasan',
        'Teknik Listrik Bandara',
        'Teknik Ekonomi Konstruksi (Quantity Surveyor)',
        'Teknik Sistem Perkapalan',
        'Teknik Pengairan (Sumber Daya Air)',
        'Meteorologi Terapan',
        'Arsitektur Lanskap',
        'Teknik Konversi Energi',
        'Teknik Perpipaan',
        'Lainnya',
    ]];

class jurusanPendidikanSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        foreach (JURUSAN['nama_jurusan'] as $i=>$r){
            \App\JurusanPendidikan::create([
                'nama_jurusan_pendidikan' => $r,
            ]);
        }
    }
}
